### ISSUE TITLE
Files wrongly defined in MANIFEST.in

### ISSUE THREAD

**Issue by h4m** [rwl/muntjac#16]
Hi,

I've got the following error when I start muntjac:
# muntjac
Traceback (most recent call last):
  File "/bin/muntjac", line 9, in <module>
    load_entry_point('Muntjac==1.1.1', 'console_scripts', 'muntjac')()
  File "/usr/lib/python2.7/site-packages/muntjac/main.py", line 111, in main
    cssapp = DirectoryApp(join(dirname(**file**), 'public', 'css'))
  File "/usr/lib/python2.7/site-packages/paste/fileapp.py", line 275, in **init**
    assert os.path.isdir(self.path)
AssertionError

I've noticed some errors during the build process:
python setup.py build
...
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching 'muntjac/public/VAADIN/favicon.ico'
warning: no files found matching '*' under directory 'muntjac/public/'
...

They are caused by errors in the MANIFEST.in file:

include LICENSE
include README
include CHANGELOG
include Makefile
include app.yaml
include conf.ini
include epydoc.config
include muntjac/public/VAADIN/README
include muntjac/public/VAADIN/favicon.ico
recursive-include muntjac/public/ *

should be

include LICENSE
include README.rst
include CHANGELOG
include Makefile
include app.yaml
include conf.ini
include epydoc.config
include muntjac/public/VAADIN/README
recursive-include muntjac/public *

Patch file:
diff -uNr MANIFEST.in.pristine MANIFEST.in
--- MANIFEST.in.pristine    2012-09-22 12:58:44.000000000 +0200
+++ MANIFEST.in 2012-10-26 16:32:37.090044189 +0200
@@ -1,10 +1,9 @@
 include LICENSE
-include README
+include README.rst
 include CHANGELOG
 include Makefile
 include app.yaml
 include conf.ini
 include epydoc.config
 include muntjac/public/VAADIN/README
-include muntjac/public/VAADIN/favicon.ico
-recursive-include muntjac/public/ *
+recursive-include muntjac/public *

**Comment by rwl** [comment]
Thank you for raising this issue. I have pushed the changes to master and will update PyPI soon.
