### ISSUE TITLE
inner class translation

### ISSUE THREAD

**Issue by hrazdil** [rwl/muntjac#6]
In Java code in inner classes is implicit nonkeyword identificator of outer this compiled as this$0. This was in the Muntjac translation overlooked:

<pre>
--- a/ui/abstract_select.py     Thu Mar 29 15:25:00 2012 +0200
+++ b/ui/abstract_select.py     Fri Apr 13 11:22:39 2012 +0200
@@ -368,7 +368,7 @@
         @return: newItemHandler
         """
         if self._newItemHandler is None:
-            self._newItemHandler = DefaultNewItemHandler()
+            self._newItemHandler = DefaultNewItemHandler(self)
         return self._newItemHandler
 
 
@@ -1368,31 +1368,35 @@
     addition like database inserts.
     """
 
+    def __init__(self, aSelect):
+        self.aSelect = aSelect
+
     def addNewItem(self, newItemCaption):
+        aSelect = self.aSelect
         # Checks for readonly
-        if self.isReadOnly():
+        if aSelect.isReadOnly():
             raise prop.ReadOnlyException()
 
         # Adds new option
-        if self.addItem(newItemCaption) is not None:
+        if aSelect.addItem(newItemCaption) is not None:
 
             # Sets the caption property, if used
-            if self.getItemCaptionPropertyId() is not None:
+            if aSelect.getItemCaptionPropertyId() is not None:
                 try:
-                    prop = self.getContainerProperty(newItemCaption,
-                            self.getItemCaptionPropertyId())
+                    prop = aSelect.getContainerProperty(newItemCaption,
+                            aSelect.getItemCaptionPropertyId())
                     prop.setValue(newItemCaption)
                 except prop.ConversionException:
                     # The conversion exception is safely ignored, the
                     # caption is just missing
                     pass
 
-            if self.isMultiSelect():
-                values = set(self.getValue())
+            if aSelect.isMultiSelect():
+                values = set(aSelect.getValue())
                 values.add(newItemCaption)
-                self.setValue(values)
+                aSelect.setValue(values)
             else:
-                self.setValue(newItemCaption)
+                aSelect.setValue(newItemCaption)
 
 
 class IItemSetChangeEvent(container.IItemSetChangeEvent):
</pre>

**Comment by rwl** [comment]
Patch applied to master.
