### ISSUE TITLE
table collapsed columns

### ISSUE THREAD

**Issue by hrazdil** [rwl/muntjac#7]
If some columns are collapsed, then are bad calculated column coordinate. This is possible to see in  <em>/sampler#TableColumnCollapsing</em>.

<pre>
--- a/ui/table.py       Thu Mar 29 15:25:00 2012 +0200
+++ b/ui/table.py       Wed Apr 18 15:07:46 2012 +0200
@@ -1439,8 +1439,10 @@
                 generatedRow =  None
             cells[self.CELL_GENERATED_ROW][i] = generatedRow
 
+            collapsed = 0
             for j in range(cols):
                 if self.isColumnCollapsed(colids[j]):
+                    collapsed += 1
                     continue
                 p = None
                 value = ''
@@ -1503,7 +1505,7 @@
                 if isinstance(value, IComponent):
                     self.registerComponent(value)
 
-                cells[self.CELL_FIRSTCOL + j][i] = value
+                cells[self.CELL_FIRSTCOL + j - collapsed][i] = value
 
             # Gets the next item id
             if isinstance(self.items, container.IIndexed):
</pre>

**Comment by rwl** [comment]
Fixed with pull request #8.
